index:
   path: /
   controller: App\Controller\HomepageController::index

about:
   path: /about/
   controller: App\Controller\AboutController::index

contact:
   path: /contact/
   controller: App\Controller\ContactController::index

thanks:
   path: /thanks/
   controller: App\Controller\ContactController::thanks 



